# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8b549ab35733c4b0142f17b75215ae3b5a677f09719766b8c89f32c2e0aa4541d2f44adeb65ad0c0e497b2d4bf82137036512df647244dd3320dc2415e6775f

test:
  secret_key_base: 18b2ab8b0796fbb33dc1651cfc7ff0ed18cfdadd6cb4142e1ca960cbf5a746d6a8a0f3b5dbe63555002612f6a0062f457fa1126fafe76c2103fccb5bcc53efec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
